# Generated by Django 4.0.5 on 2022-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_coefficient', models.CharField(max_length=50)),
                ('second_coefficient', models.CharField(max_length=50)),
                ('third_coefficient', models.CharField(max_length=50)),
            ],
        ),
    ]
